name: Update Measles Data

on:
  schedule:
    # every day at 16:00 UTC
    - cron: '0 16 * * *'
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout Pages repo to commit back updated data
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Checkout Meaghan's measles‑pipeline repo
      - name: Checkout measles-pipeline repo
        uses: actions/checkout@v3
        with:
          repository: mmcalend/USMeaslesData
          path: measles-pipeline

      # Set up R to run the pipeline script
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Install dependencies
      - name: Install R dependencies
        working-directory: measles-pipeline
        run: |
          Rscript -e 'install.packages(c("readr", "stringr", "dplyr", "tidyr", "MMWRweek", "jsonlite"))'

      # Run the measles pipeline and move outputs to Pages site
      - name: Run measles pipeline
        working-directory: measles-pipeline
        run: |
          Rscript daily_measles.R
          mv YearlyComparison.json USMeaslesCases.csv ../docs/data/

      # Commit the refreshed data back into Pages repo
      - name: Commit updated CSVs
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "chore: update measles data"
          add: |
            docs/data/USMeaslesCases.csv
            docs/data/YearlyComparison.json
