name: Update Measles Data

on:
  schedule:
    # every day at 16:00 UTC
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout Pages repo to commit back updated data
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up python to run the pipeline script
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies (added arcgis package)
      - name: Install dependencies
        run: pip install requests pandas arcgis

      # Run the measles pipeline 
      - name: Run measles pipeline
        run: python scripts/fetch_measles_data.py

      # NEW: Update ArcGIS Online layers
      - name: Update ArcGIS Online layers
        env:
          ARCGIS_USERNAME: ${{ secrets.ARCGIS_USERNAME }}
          ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}
          ARCGIS_COUNTY_LAYER_ID: ${{ secrets.ARCGIS_COUNTY_LAYER_ID }}
          ARCGIS_STATE_MONTH_LAYER_ID: ${{ secrets.ARCGIS_STATE_MONTH_LAYER_ID }}
        run: python scripts/update_arcgis.py

      # Commit the refreshed data back into Pages site
      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "chore: update measles data"
          add: docs/data/USMeaslesCases.csv
