name: Update Measles Data

on:
  schedule:
    # every day at 16:00 UTC
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # arcgis 2.3.0 works well here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas arcgis==2.3.0

      # Your data fetch step (unchanged)
      - name: Run measles pipeline
        run: python scripts/fetch_measles_data.py

      # Update ArcGIS Online layers using REFRESH->ACCESS token
      - name: Update ArcGIS Online layers
        env:
          AGO_CLIENT_ID: ${{ secrets.AGO_CLIENT_ID }}
          AGO_CLIENT_SECRET: ${{ secrets.AGO_CLIENT_SECRET }}   # omit if you’re using PKCE/public app
          AGO_REFRESH_TOKEN: ${{ secrets.AGO_REFRESH_TOKEN }}
          ARCGIS_RAW_MEASLES: ${{ secrets.ARCGIS_RAW_MEASLES }}
          ARCGIS_STATE_MONTH: ${{ secrets.ARCGIS_STATE_MONTH }}
        run: python scripts/update_arcgis.py

      - name: Commit updated CSV
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "chore: update measles data"
          add: docs/data/USMeaslesCases.csv
